In [1]:
print("Let's get started!")
# Notes: https://www.learnpytorch.io/00_pytorch_fundamentals/

Let's get started!


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


1.13.1


### Intro to Tensors

Scalar: Scalar: A scalar is a single numerical value, which is an element of a field, such as real or complex numbers. Scalars have no direction or magnitude and only represent a magnitude of a quantity.

Vector: Vector: A vector is an ordered array of numbers, which represents a magnitude and a direction. Vectors have both magnitude and direction, and can be added, subtracted, and scaled. Vectors are used to represent physical quantities such as velocity or force.

MATRIX: A matrix is a two-dimensional array of numbers, where each element of the matrix represents a scalar. Matrices are used to represent linear transformations and are fundamental in many mathematical operations, such as solving systems of linear equations and computing eigenvalues and eigenvectors.

TENSOR: A tensor is a multi-dimensional array of numbers, which can be thought of as a generalization of scalars, vectors, and matrices. Tensors can have any number of dimensions, and they are used to represent multi-dimensional arrays of data in various fields, such as image processing, computer graphics, and machine learning. Tensors are a powerful tool for representing and manipulating high-dimensional data


In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get the number within the tensor (This only works with one element tensors)
scalar.item()

7

In [6]:
# Vectors
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
print(f'ndim: {TENSOR.ndim}')
print(f'shape: {TENSOR.shape}')

ndim: 3
shape: torch.Size([1, 3, 3])


### Creating Random tensors

In [14]:
random_tensor = torch.rand(3, 4, 10)
random_tensor

tensor([[[0.5832, 0.7698, 0.6906, 0.0504, 0.9005, 0.1609, 0.2261, 0.5056,
          0.9495, 0.9461],
         [0.2672, 0.7762, 0.6474, 0.5488, 0.1574, 0.2398, 0.0074, 0.9096,
          0.0103, 0.5879],
         [0.0123, 0.6528, 0.7615, 0.1956, 0.3988, 0.6294, 0.1904, 0.0867,
          0.8438, 0.9888],
         [0.1008, 0.7665, 0.7167, 0.3119, 0.4173, 0.3568, 0.2031, 0.4134,
          0.0621, 0.6815]],

        [[0.8603, 0.6899, 0.7058, 0.7083, 0.0295, 0.0100, 0.6576, 0.9216,
          0.7362, 0.6796],
         [0.8156, 0.3065, 0.4881, 0.8441, 0.9941, 0.2854, 0.2215, 0.7303,
          0.3027, 0.7183],
         [0.9543, 0.1761, 0.3778, 0.6276, 0.7738, 0.3574, 0.7811, 0.5845,
          0.3769, 0.6893],
         [0.1408, 0.6898, 0.4293, 0.1258, 0.0657, 0.9473, 0.6397, 0.1913,
          0.1075, 0.7738]],

        [[0.8070, 0.1483, 0.7755, 0.7721, 0.6200, 0.3932, 0.5656, 0.7190,
          0.0658, 0.5869],
         [0.3147, 0.4289, 0.6724, 0.6164, 0.0783, 0.3366, 0.0405, 0.9668,
          0.4

In [15]:
print(f'ndim: {random_tensor.ndim}')
print(f'shape: {random_tensor.shape}')

ndim: 3
shape: torch.Size([3, 4, 10])


In [16]:
# Create a random tensor that is similar in shape to that of an image:
random_image_tensor = torch.rand(size=(244,244, 3)) # height, width, color channels

In [17]:
print(f'ndim: {random_image_tensor.ndim}')
print(f'shape: {random_image_tensor.shape}')

ndim: 3
shape: torch.Size([244, 244, 3])


### Create a tensor with all zeros or all ones

In [18]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
# Checking the data type:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
 #Range with steps:
one_to_hundred = torch.arange(0,101, step=5)
one_to_hundred

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100])

In [23]:
print(f'{one_to_hundred.ndim}')
print(f'{one_to_hundred.shape}')
print(f'{one_to_hundred.dtype}')

1
torch.Size([21])
torch.int64


In [24]:
# Creating tensors like:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
Notes: 3 biggest error you will run into are:
1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not the right device

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                dtype=None, # Data type of the tensor
                                device=None, # CPU or cuda AKA GPU
                                requires_grad=False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [26]:
print(f'dtype: {float_32_tensor.dtype}')
print(f'shape: {float_32_tensor.shape}')
print(f'ndim: {float_32_tensor.ndim}')

dtype: torch.float32
shape: torch.Size([3])
ndim: 1


In [27]:
# Convert the type from 32 to 16 
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
multiply_tensors = float_32_tensor * float_16_tensor
multiply_tensors.dtype

torch.float32

### Matrix multiplication

In [29]:
tensor = torch.tensor([1, 2, 3])


In [30]:
tensor * tensor


tensor([1, 4, 9])

In [31]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [32]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [33]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 428 µs, sys: 826 µs, total: 1.25 ms
Wall time: 1.04 ms


tensor(14)

In [34]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 60 µs, sys: 11 µs, total: 71 µs
Wall time: 60.8 µs


tensor(14)

In [35]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

In [36]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])



### Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

### The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

### The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [37]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [38]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [39]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Finding the min, max, mean, sum etc (Tensor aggregation)

In [40]:
x = torch.arange(0, 100, 10) # start, end, count
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [42]:
# Find the Max 
torch.argmax(x)

tensor(9)

In [43]:
# Find the min
torch.argmin(x)

tensor(0)

In [44]:
# Reshaping, stacking, squeezing and unsqueezing tensors
import torch
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
z = x.view(3, 3) #View shares the same memory as x
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [47]:
x # notice how x changed. 

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
z, x

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [49]:
# Stack tensors on top of each other: 
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [50]:
x_reshaped.shape
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [51]:
x_reshaped.squeeze().shape
x_reshaped.squeeze()

x_squeezed = x_reshaped.squeeze()

In [52]:
print(f"Previous target: {x_reshaped.squeeze()}")
print(f"Previous target: {x_reshaped.squeeze().shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous target: torch.Size([9])

New Tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [53]:
x_original = torch.rand(size=(224, 224, 3)) # height width color channel 
print(f"original: {x_original.shape}")

# Permute the original tensor 
x_permuted = x_original.permute(2,0,1) # rearrange the axis or dim order

print(f"permuted: {x_permuted.shape}")


original: torch.Size([224, 224, 3])
permuted: torch.Size([3, 224, 224])


### Indexing with PyTorch

In [54]:
#Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [55]:
# index on the tensor: 
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
# Index on the middle bracket (dem-1)
x[0][0]

tensor([1, 2, 3])

In [57]:
x[0][0][0]

tensor(1)

In [58]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [59]:
# Get data from a dimension or column: 
x[:, :, 1]

tensor([[2, 5, 8]])

In [60]:
# get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1] # same as x[0][1][1]

tensor([5])

In [61]:
# get index 0 of 0th and 1st dimension and all values of the 2nd
x[0,0, :] # same as x[0][0]


tensor([1, 2, 3])

In [62]:
# Index on x to return 9
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [63]:
x[:, 2, 2]

tensor([9])

In [64]:
## PyTorch tensors & NumPy 
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor 

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [65]:
array = array + 1
array, tensor 

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [67]:
numpy_tensor.dtype

dtype('float32')

In [68]:
## Reproducibility using random seed
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.8995, 0.8272, 0.6298, 0.6027],
        [0.0762, 0.5323, 0.3883, 0.6806],
        [0.2543, 0.3961, 0.4747, 0.4402]])
tensor([[0.6115, 0.7870, 0.1249, 0.5040],
        [0.0896, 0.2605, 0.2826, 0.2796],
        [0.5081, 0.0758, 0.5568, 0.1727]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [69]:
# Creating reproducible tensors
import torch

RANDOM_SEED = 42
# set the random seed
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on GPUs 

1. Google colab / colab pro
2. Use your own - Take some setup and investment $$$

In [70]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()


False

In [71]:
# Setup device agnostic code:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [72]:
print("Number of GPUs:", torch.cuda.device_count())

for i in range(torch.cuda.device_count()):
    print("Device ", i, ":", torch.cuda.get_device_name(i))

print("Number of CPUs:", torch.get_num_threads())

Number of GPUs: 0
Number of CPUs: 8


In [73]:
import torch
# Putting tensors on GPUs
tensor = torch.tensor([1,2,3], device="cpu")

print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [74]:
# Move tensor to GPU (if available)
tensor_on_device = tensor.to(device)
tensor_on_device, tensor_on_device.device

(tensor([1, 2, 3]), device(type='cpu'))

In [75]:
# If a tensor is on a GPU you can't transform it to NumPy without transfering it to the CPU first. 
tensor_on_gpu = tensor.to(device)
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu



array([1, 2, 3])